"""
Plots the sampled signal, the filtered signal and the residues signal.
It reads them from the files generated by filter.cc

Use run.sh in order to compile execute and then plot automatically.
"""
import numpy as np
import matplotlib.pyplot as plt


def read_data(file: str) -> np.array:
    """
    Reads a sequence from a file and returns it as a numpy array.

    Args:
        file: file path.

    Returns:
        The sequence as a numpy array.
    """
    with open(file, 'r') as file:
        line = file.readline().strip()
        data = [float(value) for value in line.split()]

    return np.array(data)


if __name__ == "__main__":
    
    # Read signals
    signal: np.array = read_data("sampled_signal.txt")
    filtered_signal: np.array = read_data("filtered_signal.txt")
    residues: np.array = signal - filtered_signal
    t = range(1, len(signal) + 1)

    # Plot
    fig, ax = plt.subplots()

    ax.plot(t, signal, label='signal')
    ax.plot(t, filtered_signal, label='filtered_signal')
    ax.plot(t, residues, label='residues')

    ax.set_title('signal = filtered_signal + residues')
    ax.set_xlabel('t')
    ax.set_ylabel('A')

    ax.legend()
    plt.show()
